<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArticlesByLetter($letter)
    {
        return $this->createQueryBuilder('a')
            ->where("a.title LIKE :letter")
            ->andWhere('a.approved = :approved')
            ->setParameters(['letter' =>  $letter . '%',  'approved' =>true])
            ->getQuery()
            ->getResult();
    }

    public function findSameArticles($article, $user)
    {
        return $this->createQueryBuilder('a')
            ->where('a.user = :user')
            ->andWhere('a.id != :article')
            ->andWhere('a.approved = :approved')
            ->setParameters(['article' => $article, 'user' => $user, 'approved' =>true])
            ->setMaxResults(4)
            ->getQuery()
            ->getResult();

    }
}
