<?php

namespace AppBundle\Repository;

/**
 * FOSGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FOSGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
