<?php

namespace AppBundle\Repository;

/**
 * NetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAcceptedUserConnections($userId)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('(n.user = :id  or n.fromUser = :id) and n.status = :status')
            ->setParameters(['id' => $userId, 'status' => 'accepted'])
            ->addSelect('u')
            ->innerJoin('n.user', 'u')
            ->addSelect('f')
            ->innerJoin('n.fromUser', 'f');

        return $qb->getQuery()->getResult();
    }

    public function findAllUserConnections($userId)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.user = :id  or n.fromUser = :id')
            ->setParameter('id', $userId)
            ->addSelect('u')
            ->innerJoin('n.user', 'u')
            ->addSelect('f')
            ->innerJoin('n.fromUser', 'f');

        return $qb->getQuery()->getResult();
    }

    public function findConnection($userId, $fromUserId)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.user = :id  and n.fromUser = :fromUserId')
            ->orWhere('n.user = :fromUserId  and n.fromUser = :id')
            ->setParameters(['id' => $userId, 'fromUserId'=> $fromUserId]);

        return $qb->getQuery()->getResult();
    }
}
