<?php

namespace AppBundle\Repository;

/**
 * TradelandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradelandRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByNot($user)
    {
        $qb = $this->createQueryBuilder("t")
            ->where(':user NOT MEMBER OF t.users')
            ->andWhere('t.owner != :user')
            ->andWhere('t.blocked != :status')
            ->setParameters(['user' => $user, 'status' => true]);

        return $qb->getQuery()->getResult();
    }

    public function getByUser($user)
    {
        $qb = $this->createQueryBuilder("t")
            ->where(':user MEMBER OF t.users')
            ->orWhere('t.owner = :user')
            ->andWhere('t.blocked != :status')
            ->setParameters(['user' => $user, 'status' => true]);

        return $qb->getQuery()->getResult();
    }

    public function getTradelands($user, $group)
    {
        $qb = $this->createQueryBuilder("t")
            ->where(':user MEMBER OF t.users')
            ->andWhere('t.id = :group')
            ->andWhere('t.blocked != :status')
            ->setParameters(['user' => $user, 'group' => $group, 'status' => true]);

        return $qb->getQuery()->getResult();
    }

}
